description = "A sample Builder for using Move related CNBs"

[[buildpacks]]
  id = "amp-buildpacks/aptos"
  uri = "docker://ghcr.io/amp-buildpacks/aptos:0.1.0"

[[buildpacks]]
  id = "amp-buildpacks/sui"
  uri = "docker://ghcr.io/amp-buildpacks/sui:0.1.0"

[[buildpacks]]
  id = "paketo-buildpacks/procfile"
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.8"

[[order]]

  [[order.group]]
    id = "amp-buildpacks/aptos"

  [[order.group]]
    id = "amp-buildpacks/sui"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-tiny"
  id = "io.buildpacks.stacks.jammy.tiny"
  run-image = "docker.io/paketobuildpacks/run-jammy-tiny"
